version: '3'
services:
  node:
    image: node:18
    volumes:
      - ./:/var/opt/project
    ports:
      - '3000:3000'
      - '6006:6006'
      - '5173:5173'
    working_dir: /var/opt/project
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
