version: "3"
services:
  node:
    image: node:16
    volumes:
      - ./:/var/opt/project
    ports:
      - "3000:3000"
    working_dir: /var/opt/project
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
